### ISSUE TITLE
username/password secrets

### ISSUE THREAD

**Issue by rgstephens** [NaPs/helm-charts#1]
I can't username & password to work as secrets and it doesn't look like the chart has any reference to secrets. Does this still need to be added as a feature of the chart?

**Comment by NaPs** [comment]
Which chart are you talking about?

**Comment by rgstephens** [comment]
mosquitto. Couldn't figure out how to set it up based on [this](https://github.com/NaPs/helm-charts/tree/master/charts/mosquitto#secrets)

**Comment by NaPs** [comment]
Erg, this is totally irrelevant and comes from a README template I used. Sorry for that mistake.

If you want to define users for your mosquitto instance, you can use the mosquitto.users value, eg:

```
mosquitto:
  users: |-
    foo:$6$b5VUNl9bhQZ2oGuA$SvNhPFXAfnbsKmCarzEwFkJLOmzKBz3CV+rMyhEyS7VQT/e7pEYfWuL/taGSTSbgJYnbPSvMs8ZkZxnRwwZGFQ==
```

(The content of this value can be generated using mosquitto_passwd binary)
